name: TNTArena
version: '${version}'
main: farmans.tntarena.TNTArena
api-version: '1.20'
authors: [Farmans]

commands:
  tntsetup:
    description: wandka
    permission: tntarena.tntsetup
    usage: /tntsetup
  tntstart:
    description: starticek
    permission: tntarena.tntstart
    usage: /tntstart
  tntinfo:
    description: inficko
    permission: tntarena.tntinfo
    usage: /tntinfo
  tntstop:
    description: stopik
    permission: tntarena.tntstop
    usage: /tntstop
  tntdelay:
    description: delay
    permission: tntarena.tntdelay
    usage: /tntdelay <ms>
  tntfuse:
    description: cas odpaleni
    permission: tntarena.tntfuse
    usage: /tntfuse <ms>
  tntwand:
    description: trollenicko
    permission: tntarena.tntwand
    usage: /tntwand <cas odpaleni v ms> <vzdalenost blocks>

permissions:
  tntarena.tntsetup:
    default: op
  tntarena.tntstart:
    default: op
  tntarena.tntinfo:
    default: op
  tntarena.tntstop:
    default: op
  tntarena.tntdelay:
    default: op
  tntarena.tntfuse:
    default: op
